// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wallpaper_api.Models;

#nullable disable

namespace wallpaper_api.Migrations
{
    [DbContext(typeof(BancoDeDadosContext))]
    [Migration("20241018194230_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("wallpaper_api.Models.WallpaperItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WallpaperLink")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WallpaperItems");
                });
#pragma warning restore 612, 618
        }
    }
}
